######################################################################
# Automatically generated by qmake (3.0) Mon Dec 10 23:41:16 2018
######################################################################

TEMPLATE = app
TARGET = magic_square
INCLUDEPATH += includes/
QT += core gui widgets

# Input
HEADERS += includes/MagicSquare.h includes/App.h
SOURCES += src/MagicSquare.cpp src/App.cpp src/main.cpp
