#############################################################################
# Makefile for building: magic_square.app/Contents/MacOS/magic_square
# Generated by qmake (3.0) (Qt 5.6.3)
# Project:  magic_square.pro
# Template: app
# Command: /Users/vbrazas/Qt/5.6.3/clang_64/bin/qmake -o Makefile magic_square.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -std=c++11 -O2 -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -Iincludes -I../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers -I../../Qt/5.6.3/clang_64/lib/QtGui.framework/Headers -I../../Qt/5.6.3/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../Qt/5.6.3/clang_64/mkspecs/macx-clang -F/Users/vbrazas/Qt/5.6.3/clang_64/lib
QMAKE         = /Users/vbrazas/Qt/5.6.3/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = magic_square1.0.0
DISTDIR = /Users/vbrazas/projects/magic_square/.tmp/magic_square1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/vbrazas/Qt/5.6.3/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/vbrazas/Qt/5.6.3/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/MagicSquare.cpp \
		src/App.cpp \
		src/main.cpp moc_App.cpp \
		moc_MagicSquare.cpp
OBJECTS       = MagicSquare.o \
		App.o \
		main.o \
		moc_App.o \
		moc_MagicSquare.o
DIST          = ../../Qt/5.6.3/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.6.3/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.6.3/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.6.3/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.6.3/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.6.3/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.6.3/clang_64/mkspecs/common/sanitize.conf \
		../../Qt/5.6.3/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.6.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.6.3/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.6.3/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.6.3/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.6.3/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.6.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.6.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/file_copies.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/lex.prf \
		magic_square.pro includes/main.h \
		includes/App.h \
		includes/MagicSquare.h src/MagicSquare.cpp \
		src/App.cpp \
		src/main.cpp
QMAKE_TARGET  = magic_square
DESTDIR       = 
TARGET        = magic_square.app/Contents/MacOS/magic_square


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d magic_square.app/Contents/MacOS/ || mkdir -p magic_square.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: magic_square.pro ../../Qt/5.6.3/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt/5.6.3/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.6.3/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.6.3/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.6.3/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.6.3/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.6.3/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.6.3/clang_64/mkspecs/common/sanitize.conf \
		../../Qt/5.6.3/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.6.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.6.3/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.6.3/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.6.3/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.6.3/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.6.3/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.6.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.6.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/file_copies.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.6.3/clang_64/mkspecs/features/lex.prf \
		magic_square.pro \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../Qt/5.6.3/clang_64/lib/QtGui.framework/QtGui.prl \
		../../Qt/5.6.3/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile magic_square.pro
../../Qt/5.6.3/clang_64/mkspecs/features/spec_pre.prf:
../../Qt/5.6.3/clang_64/mkspecs/qdevice.pri:
../../Qt/5.6.3/clang_64/mkspecs/features/device_config.prf:
../../Qt/5.6.3/clang_64/mkspecs/common/unix.conf:
../../Qt/5.6.3/clang_64/mkspecs/common/mac.conf:
../../Qt/5.6.3/clang_64/mkspecs/common/macx.conf:
../../Qt/5.6.3/clang_64/mkspecs/common/sanitize.conf:
../../Qt/5.6.3/clang_64/mkspecs/common/gcc-base.conf:
../../Qt/5.6.3/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt/5.6.3/clang_64/mkspecs/common/clang.conf:
../../Qt/5.6.3/clang_64/mkspecs/common/clang-mac.conf:
../../Qt/5.6.3/clang_64/mkspecs/qconfig.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.6.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.6.3/clang_64/mkspecs/features/qt_functions.prf:
../../Qt/5.6.3/clang_64/mkspecs/features/qt_config.prf:
../../Qt/5.6.3/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt/5.6.3/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt/5.6.3/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.6.3/clang_64/mkspecs/features/default_pre.prf:
../../Qt/5.6.3/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt/5.6.3/clang_64/mkspecs/features/resolve_config.prf:
../../Qt/5.6.3/clang_64/mkspecs/features/default_post.prf:
../../Qt/5.6.3/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt/5.6.3/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt/5.6.3/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt/5.6.3/clang_64/mkspecs/features/warn_on.prf:
../../Qt/5.6.3/clang_64/mkspecs/features/qt.prf:
../../Qt/5.6.3/clang_64/mkspecs/features/resources.prf:
../../Qt/5.6.3/clang_64/mkspecs/features/moc.prf:
../../Qt/5.6.3/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt/5.6.3/clang_64/mkspecs/features/uic.prf:
../../Qt/5.6.3/clang_64/mkspecs/features/unix/thread.prf:
../../Qt/5.6.3/clang_64/mkspecs/features/file_copies.prf:
../../Qt/5.6.3/clang_64/mkspecs/features/mac/rez.prf:
../../Qt/5.6.3/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../Qt/5.6.3/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.6.3/clang_64/mkspecs/features/exceptions.prf:
../../Qt/5.6.3/clang_64/mkspecs/features/yacc.prf:
../../Qt/5.6.3/clang_64/mkspecs/features/lex.prf:
magic_square.pro:
../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../Qt/5.6.3/clang_64/lib/QtGui.framework/QtGui.prl:
../../Qt/5.6.3/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile magic_square.pro

qmake_all: FORCE

magic_square.app/Contents/PkgInfo: 
	@test -d magic_square.app/Contents || mkdir -p magic_square.app/Contents
	@$(DEL_FILE) magic_square.app/Contents/PkgInfo
	@echo "APPL????" > magic_square.app/Contents/PkgInfo
magic_square.app/Contents/Resources/empty.lproj: 
	@test -d magic_square.app/Contents/Resources || mkdir -p magic_square.app/Contents/Resources
	@touch magic_square.app/Contents/Resources/empty.lproj
	
magic_square.app/Contents/Info.plist: 
	@test -d magic_square.app/Contents || mkdir -p magic_square.app/Contents
	@$(DEL_FILE) magic_square.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.magic-square,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,magic_square,g" -e "s,@LIBRARY@,magic_square,g" -e "s,@TYPEINFO@,????,g" ../../Qt/5.6.3/clang_64/mkspecs/macx-clang/Info.plist.app >magic_square.app/Contents/Info.plist

all: Makefile \
		magic_square.app/Contents/PkgInfo \
		magic_square.app/Contents/Resources/empty.lproj \
		magic_square.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents includes/main.h includes/App.h includes/MagicSquare.h $(DISTDIR)/
	$(COPY_FILE) --parents src/MagicSquare.cpp src/App.cpp src/main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r magic_square.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_App.cpp moc_MagicSquare.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_App.cpp moc_MagicSquare.cpp
moc_App.cpp: includes/main.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QtWidgets \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qaccessiblewidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qerrormessage.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfilesystemmodel.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfontdialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qprogressdialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsanchorlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsgridlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayoutitem.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicslinearlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicstransform.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicswidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractitemdelegate.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractitemview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcolumnview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdatawidgetmapper.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdirmodel.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfileiconprovider.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qheaderview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qitemdelegate.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qitemeditorfactory.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlistview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtableview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtreeview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtreewidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtreewidgetitemiterator.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qformlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgesture.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgesturerecognizer.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qshortcut.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qsizepolicy.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtooltip.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qwhatsthis.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qwidgetaction.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qkeyeventtransition.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmouseeventtransition.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcommonstyle.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdrawutil.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qproxystyle.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstylefactory.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstyleoption.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstylepainter.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstyleplugin.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcolormap.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcompleter.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qscroller.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qscrollerproperties.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qundogroup.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qundostack.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qundoview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractbutton.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractscrollarea.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractslider.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractspinbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcalendarwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcommandlinkbutton.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdial.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdialogbuttonbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfocusframe.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfontcombobox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgroupbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qkeysequenceedit.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmdiarea.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmdisubwindow.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmenu.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmenubar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qprogressbar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qrubberband.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qscrollarea.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qscrollbar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qsizegrip.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qsplashscreen.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstatusbar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtabbar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtoolbar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtoolbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtoolbutton.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsversion.h \
		../../Qt/5.6.3/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.6.3/clang_64/lib/QtCore.framework/Headers/qstring.h \
		includes/MagicSquare.h \
		includes/App.h
	/Users/vbrazas/Qt/5.6.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/vbrazas/Qt/5.6.3/clang_64/mkspecs/macx-clang -I/Users/vbrazas/projects/magic_square -I/Users/vbrazas/projects/magic_square/includes -I/Users/vbrazas/Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/vbrazas/Qt/5.6.3/clang_64/lib/QtGui.framework/Headers -I/Users/vbrazas/Qt/5.6.3/clang_64/lib/QtCore.framework/Headers -F/Users/vbrazas/Qt/5.6.3/clang_64/lib includes/App.h -o moc_App.cpp

moc_MagicSquare.cpp: includes/main.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QtWidgets \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qaccessiblewidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qerrormessage.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfilesystemmodel.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfontdialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qprogressdialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsanchorlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsgridlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayoutitem.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicslinearlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicstransform.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicswidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractitemdelegate.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractitemview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcolumnview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdatawidgetmapper.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdirmodel.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfileiconprovider.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qheaderview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qitemdelegate.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qitemeditorfactory.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlistview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtableview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtreeview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtreewidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtreewidgetitemiterator.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qformlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgesture.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgesturerecognizer.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qshortcut.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qsizepolicy.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtooltip.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qwhatsthis.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qwidgetaction.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qkeyeventtransition.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmouseeventtransition.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcommonstyle.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdrawutil.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qproxystyle.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstylefactory.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstyleoption.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstylepainter.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstyleplugin.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcolormap.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcompleter.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qscroller.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qscrollerproperties.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qundogroup.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qundostack.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qundoview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractbutton.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractscrollarea.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractslider.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractspinbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcalendarwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcommandlinkbutton.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdial.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdialogbuttonbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfocusframe.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfontcombobox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgroupbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qkeysequenceedit.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmdiarea.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmdisubwindow.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmenu.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmenubar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qprogressbar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qrubberband.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qscrollarea.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qscrollbar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qsizegrip.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qsplashscreen.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstatusbar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtabbar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtoolbar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtoolbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtoolbutton.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsversion.h \
		../../Qt/5.6.3/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.6.3/clang_64/lib/QtCore.framework/Headers/qstring.h \
		includes/MagicSquare.h
	/Users/vbrazas/Qt/5.6.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/vbrazas/Qt/5.6.3/clang_64/mkspecs/macx-clang -I/Users/vbrazas/projects/magic_square -I/Users/vbrazas/projects/magic_square/includes -I/Users/vbrazas/Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/vbrazas/Qt/5.6.3/clang_64/lib/QtGui.framework/Headers -I/Users/vbrazas/Qt/5.6.3/clang_64/lib/QtCore.framework/Headers -F/Users/vbrazas/Qt/5.6.3/clang_64/lib includes/MagicSquare.h -o moc_MagicSquare.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

MagicSquare.o: src/MagicSquare.cpp includes/MagicSquare.h \
		includes/main.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QtWidgets \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qaccessiblewidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qerrormessage.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfilesystemmodel.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfontdialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qprogressdialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsanchorlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsgridlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayoutitem.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicslinearlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicstransform.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicswidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractitemdelegate.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractitemview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcolumnview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdatawidgetmapper.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdirmodel.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfileiconprovider.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qheaderview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qitemdelegate.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qitemeditorfactory.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlistview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtableview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtreeview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtreewidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtreewidgetitemiterator.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qformlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgesture.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgesturerecognizer.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qshortcut.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qsizepolicy.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtooltip.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qwhatsthis.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qwidgetaction.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qkeyeventtransition.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmouseeventtransition.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcommonstyle.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdrawutil.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qproxystyle.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstylefactory.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstyleoption.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstylepainter.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstyleplugin.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcolormap.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcompleter.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qscroller.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qscrollerproperties.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qundogroup.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qundostack.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qundoview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractbutton.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractscrollarea.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractslider.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractspinbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcalendarwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcommandlinkbutton.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdial.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdialogbuttonbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfocusframe.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfontcombobox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgroupbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qkeysequenceedit.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmdiarea.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmdisubwindow.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmenu.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmenubar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qprogressbar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qrubberband.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qscrollarea.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qscrollbar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qsizegrip.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qsplashscreen.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstatusbar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtabbar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtoolbar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtoolbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtoolbutton.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsversion.h \
		../../Qt/5.6.3/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.6.3/clang_64/lib/QtCore.framework/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MagicSquare.o src/MagicSquare.cpp

App.o: src/App.cpp includes/App.h \
		includes/main.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QtWidgets \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qaccessiblewidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qerrormessage.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfilesystemmodel.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfontdialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qprogressdialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsanchorlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsgridlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayoutitem.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicslinearlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicstransform.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicswidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractitemdelegate.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractitemview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcolumnview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdatawidgetmapper.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdirmodel.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfileiconprovider.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qheaderview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qitemdelegate.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qitemeditorfactory.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlistview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtableview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtreeview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtreewidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtreewidgetitemiterator.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qformlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgesture.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgesturerecognizer.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qshortcut.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qsizepolicy.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtooltip.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qwhatsthis.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qwidgetaction.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qkeyeventtransition.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmouseeventtransition.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcommonstyle.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdrawutil.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qproxystyle.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstylefactory.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstyleoption.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstylepainter.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstyleplugin.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcolormap.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcompleter.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qscroller.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qscrollerproperties.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qundogroup.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qundostack.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qundoview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractbutton.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractscrollarea.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractslider.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractspinbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcalendarwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcommandlinkbutton.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdial.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdialogbuttonbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfocusframe.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfontcombobox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgroupbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qkeysequenceedit.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmdiarea.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmdisubwindow.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmenu.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmenubar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qprogressbar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qrubberband.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qscrollarea.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qscrollbar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qsizegrip.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qsplashscreen.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstatusbar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtabbar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtoolbar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtoolbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtoolbutton.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsversion.h \
		../../Qt/5.6.3/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.6.3/clang_64/lib/QtCore.framework/Headers/qstring.h \
		includes/MagicSquare.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o App.o src/App.cpp

main.o: src/main.cpp includes/App.h \
		includes/main.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QtWidgets \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qaccessiblewidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qerrormessage.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfilesystemmodel.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfontdialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qprogressdialog.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsanchorlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsgridlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayoutitem.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicslinearlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicstransform.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgraphicswidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractitemdelegate.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractitemview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcolumnview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdatawidgetmapper.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdirmodel.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfileiconprovider.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qheaderview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qitemdelegate.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qitemeditorfactory.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlistview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtableview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtreeview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtreewidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtreewidgetitemiterator.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qformlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgesture.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgesturerecognizer.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qshortcut.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qsizepolicy.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtooltip.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qwhatsthis.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qwidgetaction.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qkeyeventtransition.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmouseeventtransition.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcommonstyle.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdrawutil.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qproxystyle.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstylefactory.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstyleoption.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstylepainter.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstyleplugin.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcolormap.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcompleter.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qscroller.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qscrollerproperties.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qundogroup.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qundostack.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qundoview.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractbutton.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractscrollarea.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractslider.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qabstractspinbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcalendarwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qcommandlinkbutton.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdial.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdialogbuttonbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfocusframe.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qfontcombobox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qgroupbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qkeysequenceedit.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmdiarea.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmdisubwindow.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmenu.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmenubar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qprogressbar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qrubberband.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qscrollarea.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qscrollbar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qsizegrip.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qsplashscreen.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qstatusbar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtabbar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtoolbar.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtoolbox.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtoolbutton.h \
		../../Qt/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsversion.h \
		../../Qt/5.6.3/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.6.3/clang_64/lib/QtCore.framework/Headers/qstring.h \
		includes/MagicSquare.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

moc_App.o: moc_App.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_App.o moc_App.cpp

moc_MagicSquare.o: moc_MagicSquare.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MagicSquare.o moc_MagicSquare.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

